/**
 * Historical sales-insights shapes — what the Value + Option editors expect.
 *
 * These shapes were previously generated by `features/{value,option}/mockData/`
 * deterministic generators. Phase 1 swaps the data source: the shapes stay,
 * the producer becomes a transformer over real `/sales/*` API rows. Phase 2
 * (recommendations) shares the same producers.
 */

import type { MrpBand } from '@/features/otb/types';
import type { OptionType } from '@/features/option/constants';

// ── Value editor ────────────────────────────────────────────────────────────

export interface BandLyPerformance {
  band_id: MrpBand['id'];
  units_sold: number;
  revenue: number;
  sell_through_pct: number;
  markdown_depth_pct: number;
  realized_margin_pct: number;
  doc_days: number;
  ly_share_pct: number;
}

export interface SalesInsights {
  ly_period_label: string;
  ly_total_units: number;
  ly_total_revenue: number;
  yoy_units_growth_pct: number;
  yoy_revenue_growth_pct: number;
  avg_sell_through_pct: number;
  top_band_id: MrpBand['id'];
  worst_band_id: MrpBand['id'];
  bands: BandLyPerformance[];
  trends: {
    demand_index: number;
    search_trend_pct: number;
    competitor_price_delta_pct: number;
    festival_hint?: string;
  };
}

// ── Option editor ───────────────────────────────────────────────────────────

export interface SubTypeLyPerformance {
  sub_type_key: string;
  sub_type_label: string;
  units: number;
  vol_pct: number;
  rev_pct: number;
  sell_through_pct: number;
  markdown_depth_pct: number;
  realized_margin_pct: number;
  return_pct: number;
  yoy_pct: number;
}

export interface BandOptionTypeInsights {
  band_id: MrpBand['id'];
  option_type: OptionType;
  sub_types: SubTypeLyPerformance[];
}

export interface OptionPlanInsights {
  ly_period_label: string;
  category_label: string;
  ly_total_options: number;
  ly_total_units: number;
  ly_total_revenue: number;
  ly_avg_options_per_band: number;
  ly_sell_through_pct: number;
  ly_realized_margin_pct: number;
  ly_return_pct: number;
  trend_chips: Array<{ label: string; delta_pct: number }>;
  festival_hint?: string;
  per_band_per_type: BandOptionTypeInsights[];
}
